name: Windows
on: 
  # push代码时触发workflow
  push:
    paths:
      - '*.pro'
      - 'untitled1/**'
      - '.github/workflows/untitled1.yml'
  pull_request:
    paths:
      - '*.pro'
      - 'untitled1/**'
      - '.github/workflows/untitled1.yml' 
jobs:
  build:
    name: Build
    # 运行平台， windows-latest目前是windows server 2019 
    # 参考文档 https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-2019
    strategy:
      # 矩阵配置
      matrix:
        include:
          # 5.15.2 参考 https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/windows_x86/desktop/qt5_5152/
          - qt_ver: 5.15.2
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64       
    env:
      targetName: untitled1.exe
    
    # 步骤
    steps:
     # 安装编译依赖（Windows）
      - name: Install build dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y build-essential libffi-dev zlib1g-dev
      # 安装Qt
      - name: Install Qt
        # 使用外部action。这个action专门用来安装Qt
        uses: jurplel/install-qt-action@v2
        with:
         # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          # target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          cached: 'false'
          aqtversion: '==2.0.5'   
                
      # 拉取代码
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
     
      # msvc编译
      - name: build-msvc-x64
        if: contains(matrix.qt_arch,'msvc') && contains(matrix.qt_arch,'win64')
        shell: cmd
        run: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
          cd untitled1
          qmake
          if %errorlevel% neq 0 (
              echo "qmake failed"
              exit /b %errorlevel%
          )
          nmake
          if %errorlevel% neq 0 (
              echo "nmake failed"
              exit /b %errorlevel%
          )
          REM 如果后续不需要这些环境变量，可以移除下面的语句
          echo winSdkDir=%WindowsSdkDir% >> %GITHUB_ENV%
          echo winSdkVer=%WindowsSdkVersion% >> %GITHUB_ENV%
          echo vcToolsInstallDir=%VCToolsInstallDir% >> %GITHUB_ENV%
          echo vcToolsRedistDir=%VCToolsRedistDir% >> %GITHUB_ENV%
